### ISSUE TITLE
Hmmm

### ISSUE THREAD

**Issue by Spaceish** [Joonsss/discord-token-joiner#4]
![Screenshot_2023-04-24-21-56-56-299_com.android.chrome.jpg](https://user-images.githubusercontent.com/63191158/234090728-d5fc5098-fe2a-40a6-82c9-1778788b574b.jpg)
```
Lmao we got another one
```
stealer
Bro, please make tools without putting stealers in them

**Comment by Joonsss** [comment]
fake lmao tell me the line

**Comment by Spaceish** [comment]
> fake lmao tell me the line

Line 68
![Screenshot_2023-04-27-10-23-35-439-edit_com.github.android.jpg](https://user-images.githubusercontent.com/63191158/234789787-024e985a-733f-4e26-8f74-16f663a50f57.jpg)

It's encoded in base 64

**Comment by Joonsss** [comment]
removed
